[[redirects]]
  from = "/dashboard"
  to = "/#/dashboard"
  status = 200
  
[[redirects]]
    from = "/request-form"
    to = "/#/request-form"
    status = 200

[[redirects]]
  from = "/indicator"
  to = "/#/indicator"
  status = 200